articles/urls.py
from django.conf.urls import patterns, include, url
from articles.views import ArticleDetail, ArticleList
urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', ArticleDetail.as_view(), name='article-by-pk'),
    url(r'^(?P<slug>[-\w]+)/$', ArticleDetail.as_view(), name='read-article'),
    url(r'^$', ArticleList.as_view(), name='list-articles'),
)

issue/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from issue.views import IssueDetail, IssueList
urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', IssueDetail.as_view(), name='view-issue'),
    url(r'^$', IssueList.as_view(), name='list-issues'),
)

sirius/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from sirius import views
from django.contrib.flatpages.views import flatpage

from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.home, name='home'),
    # url(r'^sirius/', include('sirius.foo.urls')),
    url(r'^issue/', include('issue.urls')),
    url(r'^article/', include('articles.urls')),
    url(r'^squiggle/', include('issue.urls_squiggle')),
    url(r'^person/', include('people.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)
#Flatpages

urlpatterns += patterns('',
    (r'^dispatch.wsgi/(?P<url>.*/)$', flatpage),
    (r'^(?P<url>.*/)$', flatpage),
)

articles/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify

class Article(models.Model):
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=150, blank=True)
    title_show = models.BooleanField('Display title', default=True)
    header_image = models.ForeignKey('media.Picture', blank=True, null=True)
    thumbnail = models.ForeignKey('media.Picture', related_name='article_thumbnail', blank=True, null=True)
    issue = models.ForeignKey('issue.Issue', blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    edit_date = models.DateTimeField(blank=True, null=True)
    section = models.ForeignKey('Section')
    series = models.ForeignKey('Series', blank=True, null=True)
    part_number = models.IntegerField(blank=True, default=0)
    part_name = models.CharField(max_length=150, blank=True)
    persons = models.ManyToManyField('people.Person')
    sources = models.ManyToManyField('media.Source', blank=True)
    content = models.TextField()
    blurb = models.TextField(blank=True)
    show_blurb = models.BooleanField('Show blurb in full article?', default=False)
    footer = models.TextField(blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    pages = models.CommaSeparatedIntegerField(max_length=30)
    def __unicode__(self):
        return '%s %d' % (self.title, self.part_number)
    def get_id(self):
        if self.issue:
            return '/%d/%d-%s' % (self.issue.number, int(self.pages.split(',')[0]), slugify(self.title))
        else:
            return format('/web/%(year)d/%(month)d/%(day)d/%(hour)d-%(minute)d-%(title)s' % {
                'year': self.date.year,
                'month': self.date.month,
                'day': self.date.day,
                'hour': self.date.hour,
                'minute': self.date.minute,
                'title': slugify(self.title) })
    def get_absolute_url(self):
        return reverse('read-article', kwargs={'slug':self.slug})
    def generate_slug(self):
        '''
        Outputs the default, auto-generated slug for the given article, using 
        other properties to create a (hopefully) unique slug.
        Note that this only outputs the slug; the saving is done in this 
        model's modified save() method.
        '''
        if self.issue is not None:
            slug = '%d-%d-%s' % (
                self.issue.number, 
                int(self.pages.split(',')[0]), 
                slugify(self.title))
        elif self.date is not None:
            slug = 'web-%d%d%d-%s' % (
                self.date.year, 
                self.date.month, 
                self.date.day, 
                slugify(self.title))
        else:
            # Unable to generate slug from either issue or date fields
            slug = self.slug
        return slug
    def save(self, *args, **kwargs):
        # Set the slug if field is blank
        if self.slug == 'auto' or not self.slug:
            self.slug = self.generate_slug()
        # Delete annoying '<br>' from blurb
        if self.blurb == '<br>':
            self.blurb = ''
        # Do the real save
        super(Article, self).save(*args, **kwargs)
    class Meta:
        get_latest_by = 'issue'
class Series(models.Model):
    title = models.CharField(max_length=150, blank=True)
    header_image = models.ForeignKey('media.Picture', blank=True, null=True)
    tagline = models.CharField(max_length=150, blank=True)
    def __unicode__(self):
        return self.title
class Section(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(primary_key=True)
    description = models.TextField(default='<p>No description!</p>')
    submission_instructions = models.TextField(blank=True)
    icon_left = models.URLField(blank=True)
    icon_right = models.URLField(blank=True)
    def __unicode__(self):
        return self.name
class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    def __unicode__(self):
        return self.name

articles/views.py
from django.views import generic
from articles.models import Article, Series, Section, Tag
class ArticleDetail(generic.DetailView):
    model = Article
    template_name = 'articles/article.htm'
    
    def get_context_data(self, **kwargs):
        context = super(ArticleDetail, self).get_context_data(**kwargs)
        context['page_icon'] = self.object.section.icon_left
        context['page_section'] = self.object.section.name
        return context
class ArticleList(generic.ListView):
    model = Article
    template_name = 'articles/article_list.htm'
    
    def get_context_data(self, **kwargs):
        context = super(ArticleList, self).get_context_data(**kwargs)
        context['page_icon'] = 'http://i.minus.com/iDhR7DotZgasx.png'
        context['page_section'] = 'Articles'
        return context

articles/templates/articles/article.htm
{% extends 'base.html' %}
{% block title %}{{article.title}} - Sirius{% endblock %}
{% block content %}
{% if article.title_show %}<h1>{{article.title}}</h1>
{% if article.part_number != 0%}<p class="text-muted">Part {{article.part_number}}{% if article.part_name %}: {{article.part_name}}{% endif %}</p>{% endif %}
{% elif article.header_image %}<h1><img src="{{article.header_image.get_absolute_url}}" alt="{{article.title}}" class="img-responsive center-block"></h1>{% endif %}
{% if article.show_blurb %}<div class="lead">{{article.blurb|safe}}</div>{% endif %}
{% autoescape off %}
{{article.content}}<span class="fa fa-stop"></span>
{% if article.series %}
<br>
<ul class="pager">
  {% with p=article.series.article_set.all.get_previous_by_date n=article.series.article_set.all.get_next_by_date %}
    {% if p %}<li class="previous"><a href="{{p.get_absolute_url}}">&larr; {% firstof p.title p.event %}</a></li>{% endif %}
    {% if n %}<li class="next"><a href="{{n.get_absolute_url}}">{% firstof n.title n.date %} &rarr;</a></li>{% endif %}
  {% endwith %}
</ul>
{% endif %}
<hr>
<div class="footer">Article by {% for p in article.persons.all %}<a href="/person/{{p.id}}">{{p.name}}</a>, {% endfor %}published {% if article.issue %} on {{article.issue.start_date}} in <a href="{{article.issue.get_absolute_url}}">Sirius #{{article.issue.number}} "{{article.issue.name}}"</a>.{% else %}online on {{article.date|date:'d M Y'}} at {{article.date|date:'P'}}{% endif %}{% if article.edit_date %}, and was last edited on {{article.edit_date|date:'d M Y'}} at {{article.edit_date|date:'P'}}{% endif %}{% if article.footer %} {{article.footer}}{% endif %}</div>
{% endautoescape %}
<hr>
<div id="disqus_thread"></div>
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'siriusmag'; // required: replace example with your forum shortname
      var disqus_identifier = '{{article.slug}}';
      var disqus_title = '{{article.title}}{% if article.part_number > 0 %} [Part {{article.part_number}}{% if article.part_name %}: {{article.part_name}}{% endif %}]{% endif %}';
      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
{% endblock %}

articles/templates/articles/article_list.htm
{% extends 'base.html' %}
{% block title %}Article list - Sirius{% endblock %}
{% block content %}
{% autoescape off %}
{% for article in article_list %}
<div class="article-snippet">
    <h2><a href="{{article.get_absolute_url}}">{{article.title}}</a> <small>{% for tag in article.tags.all %}<span class="label label-default">{{tag}}</span> {% endfor %}</small></h2>
    {% if article.series %}<p class="text-muted">Part {{article.part_number}}{% if article.part_name %}: {{article.part_name}}{% endif %}</p>{% endif %}
    <!--<img class="img img-responsive img-thumbnail img-sirius-thumbnail pull-left" src="{% if article.thumbnail %}{{article.thumbnail.get_absolute_url}}{% else %}http://placehold.it/200x150&text={{article.title}}{% endif %}" alt="Thumbnail for {{article.title}}" />-->
    {% if article.blurb %}{{article.blurb}}{% else %}{{article.content|striptags|truncatewords:60}}{% endif %}
    <p class="pull-right"><a href="{{article.get_absolute_url}}" class="btn btn-default">{% if article.section.icon_right %}<img height="30px" src="{{article.section.icon_right}}" alt="[{{article.section}}]">{% else %}[{{article.section}}]{% endif %} Read more</a></p>
</div>
{% endfor %}
{% endautoescape %}
{% endblock %}